// providers/lodgify.js
// Lodgify PMS API integration (https://docs.lodgify.com).
//
// STATUS: SCAFFOLD — Not yet exercised against a live API key. Auth scheme,
// base URL, endpoint paths and pagination model are taken directly from the
// public Lodgify v2 docs. Response parsing is best-effort and MUST be
// verified against a real /v2/reservations/bookings payload before this
// provider is enabled in production (registered in the UI / used by a real
// property).
//
// Auth: API Key in the `X-ApiKey` HTTP header.
//   Single key per property, generated by the property owner from their
//   Lodgify admin and shared with us. No OAuth, no partner program, no
//   certification — the simplest auth model of all our PMSes.
//   Store schema:
//     api_key_secret : the X-ApiKey value (per-property API key)
//     api_key_name   : Lodgify propertyID (numeric) — required to filter
//                      bookings to this specific property when the API key
//                      has access to multiple properties under one account.
//
// Base: https://api.lodgify.com/v2 (some endpoints are still v1; we use
//   v2 wherever it exists per Lodgify's own recommendation).
//
// Sync: GET /v2/reservations/bookings
//   Filters used:
//     - `updatedSince` (ISO datetime) for incremental sync
//     - `stayFilter=Current` for "in-house" bookings (or `Upcoming` for
//       arrivals in the window)
//     - `page` + `size` for pagination (default page=1, size=50; we
//       request size=100 and walk pages until the response is short)
//   Response: { count, items: [{ id, user_id, arrival, departure,
//     property_id, rooms: [{ room_type_id, guest_breakdown, ... }],
//     status (Open/Tentative/Booked/Declined), ... }] }
//
// Listings: GET /v1/properties (then /v1/properties/{id}/rooms/{rid} for
//   per-room detail). v1 because v2 doesn't yet expose the full property
//   list with rooms in a single call.
//
// Status mapping (Lodgify enum → Horizon status):
//   Booked / Open (in stay window) → 'confirmed'
//   Tentative                       → 'confirmed' (treat as held; let
//                                      validation downstream still allow)
//   Declined                        → 'cancelled'
//   Booking also has `canceled_at` — if non-null, force 'cancelled'.
//
// ── BREAKFAST DETECTION — DESIGN CHOICE ─────────────────────────────────────
// Critical gap: Lodgify's booking response does NOT carry a board-basis /
// meal-plan / breakfast-included field. The booking only carries
// `room_type_id` and guest breakdown. This is because Lodgify is primarily
// a vacation-rental PMS where meal plans are uncommon.
//
// We therefore default to a **per-room toggle**: the property tells us via
// the Horizon admin whether each Lodgify-mapped room "always includes
// breakfast" or "never includes breakfast". This is encoded by reusing
// `stores.meal_plan_breakfast_values`:
//   - If empty/null → all bookings on this room include breakfast (true).
//   - If set to a magic value like 'NEVER' → all bookings on this room
//     do NOT include breakfast.
//   - If set to a comma-separated list → reserved for future rate-plan
//     name matching, once we know whether Lodgify's add-ons or rate model
//     gives us such a field.
//
// This may be revised once Lodgify (Myrsini Pappa) confirms whether
// breakfast is typically modeled as an add-on (/v1/properties/{id}/rates/
// addons) or as a rate-plan attribute.

import {
  upsertBookings,
  startLog,
  endLog,
  markRoomSynced,
  offsetDate,
  supabase,
} from './_shared.js';

const BASE_URL = 'https://api.lodgify.com';
const PAGE_SIZE = 100;

// Module-level cache: `${store_id}:${fromIso}:${toIso}` → bookings[].
// Survives within a warm Lambda container only.
const bookingsCache = new Map();

// ─── Sync ────────────────────────────────────────────────────────────────────
export async function syncLodgify(room, { lookbackDays, forwardDays }) {
  const logId = await startLog(room.id, 'lodgify');
  const fromIso = offsetDate(-lookbackDays);
  const toIso   = offsetDate(forwardDays);

  const store = room.stores;
  const apiKey     = store?.api_key_secret;
  const propertyID = store?.api_key_name;
  if (!apiKey) {
    const err = 'Missing api_key_secret (Lodgify X-ApiKey) on linked store — skipped';
    await endLog(logId, 'failed', {}, err);
    return { room_id: room.id, name: room.name, provider: 'lodgify', error: err };
  }

  try {
    // Lodgify's getAllBookings does NOT support filtering by check-in window
    // directly — it has `updatedSince` (modification date) and a `stayFilter`
    // enum that only takes coarse buckets (Upcoming/Current/Historic/All).
    // For our 30-back / 90-forward window we fetch with `stayFilter=All`
    // and rely on `updatedSince` for incremental syncs after the first run,
    // then filter to the window client-side. To bound the first sync, we
    // pass `updatedSince=fromIso` (the lookback floor).
    const cacheKey = `${room.store_id}:${fromIso}:${toIso}`;
    let allBookings = bookingsCache.get(cacheKey);

    if (!allBookings) {
      allBookings = await fetchAllBookings(
        { apiKey, propertyID },
        { updatedSince: `${fromIso}T00:00:00Z`, stayFilter: 'All' }
      );
      bookingsCache.set(cacheKey, allBookings);
    }

    // Client-side filter:
    // 1) Only this property (defense — apiKey scope may already enforce it)
    // 2) Only the bookings that hit our window: arrival <= toIso AND
    //    departure >= fromIso (overlap, not strict containment).
    // 3) Only the bookings that cover this physical room — match on
    //    room_type_id == platform_id (we store room_type_id in platform_id
    //    for Lodgify because that's the granularity reservations attach to).
    const ours = allBookings
      .filter(b => !propertyID || String(b.property_id) === String(propertyID))
      .filter(b => bookingOverlapsWindow(b, fromIso, toIso))
      .filter(b => bookingCoversRoom(b, room.platform_id));

    // Breakfast detection context (see DESIGN CHOICE above).
    const transform = (b) => transformBooking(b, room.platform_id, store);

    const stats = await upsertBookings(room, 'lodgify', ours, transform, fromIso);

    await markRoomSynced(room.id);
    await endLog(logId, 'success', stats);
    return { room_id: room.id, name: room.name, provider: 'lodgify', ...stats };
  } catch (err) {
    await endLog(logId, 'failed', {}, err.message);
    return { room_id: room.id, name: room.name, provider: 'lodgify', error: err.message };
  }
}

// ─── Listings ────────────────────────────────────────────────────────────────
export async function fetchLodgifyListings(store) {
  const apiKey     = store.api_key_secret;
  const propertyID = store.api_key_name;
  if (!apiKey) {
    throw new Error('No Lodgify credentials set on this store. Add the X-ApiKey value (api_key_secret) and (optionally) the Lodgify propertyID (api_key_name) in Store settings.');
  }

  // v1/properties returns all properties accessible to this API key.
  // Each property includes its room types; we flatten them into one
  // listing per room type. If `propertyID` is set, filter to just that
  // property.
  const properties = await lodgifyGet(`${BASE_URL}/v1/properties`, { apiKey }, {});
  const propsArr = Array.isArray(properties) ? properties : (properties?.items || []);
  const filtered = propertyID
    ? propsArr.filter(p => String(p.id) === String(propertyID))
    : propsArr;

  const listings = [];
  for (const prop of filtered) {
    const rooms = Array.isArray(prop?.rooms) ? prop.rooms : [];
    for (const r of rooms) {
      const roomTypeId = r.room_type_id ?? r.id;
      if (!roomTypeId) continue;
      listings.push({
        platform_id: String(roomTypeId),
        name: `${prop.name || `Property ${prop.id}`} — ${r.name || `Room ${roomTypeId}`}`,
        capacity: r.max_persons ?? r.max_guests ?? null,
        platform: 'lodgify',
      });
    }
  }

  return {
    statusCode: 200,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ store_id: store.id, listings, platform: 'lodgify' }),
  };
}

// ─── Fetchers ────────────────────────────────────────────────────────────────

async function fetchAllBookings({ apiKey, propertyID }, { updatedSince, stayFilter }) {
  const all = [];
  let page = 1;
  const MAX_PAGES = 100; // bounds runaway pagination

  while (page <= MAX_PAGES) {
    const json = await lodgifyGet(
      `${BASE_URL}/v2/reservations/bookings`,
      { apiKey },
      {
        page,
        size: PAGE_SIZE,
        includeCount: false,
        stayFilter,
        updatedSince,
      }
    );

    const items = Array.isArray(json?.items) ? json.items : [];
    all.push(...items);
    if (items.length < PAGE_SIZE) break;
    page += 1;
  }
  return all;
}

// Single GET wrapper. Lodgify auth = X-ApiKey header. Responses are JSON;
// errors come back with a 4xx/5xx status code and a JSON body.
async function lodgifyGet(url, { apiKey }, params) {
  const qs = new URLSearchParams();
  for (const [k, v] of Object.entries(params || {})) {
    if (v !== undefined && v !== null && v !== '') qs.set(k, String(v));
  }
  const fullUrl = qs.toString() ? `${url}?${qs.toString()}` : url;

  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch(fullUrl, {
      headers: {
        'X-ApiKey': apiKey,
        Accept: 'application/json',
      },
    });

    if (res.status === 429) {
      const retryAfter = parseInt(res.headers.get('retry-after') || '1', 10);
      await sleep(Math.max(500, retryAfter * 1000));
      continue;
    }

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Lodgify API error ${res.status} on ${url}: ${text.slice(0, 300)}`);
    }
    return await res.json();
  }
  throw new Error(`Lodgify API: rate-limited after 3 attempts on ${url}`);
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ─── Transforms ──────────────────────────────────────────────────────────────

function transformBooking(b, roomPlatformId, store) {
  const external_id = String(b.id ?? '');
  const check_in    = toIsoDate(b.arrival);
  const check_out   = toIsoDate(b.departure);

  // Guest count: prefer guest_breakdown across the rooms[] arrays.
  let guests = 0;
  const rooms = Array.isArray(b.rooms) ? b.rooms : [];
  for (const r of rooms) {
    const adults   = parseInt(r?.guest_breakdown?.adults   ?? 0, 10);
    const children = parseInt(r?.guest_breakdown?.children ?? 0, 10);
    guests += (adults + children);
  }
  if (!guests) guests = parseInt(b?.guest?.adults ?? 0, 10) || 1;

  // Status mapping (see header).
  const rawStatus = String(b.status ?? '').toLowerCase();
  let status = 'confirmed';
  if (b.canceled_at) status = 'cancelled';
  else if (rawStatus === 'declined') status = 'cancelled';

  // Breakfast detection — per-room toggle (see DESIGN CHOICE block at top).
  // Default = include breakfast. Set the magic value 'NEVER' in
  // stores.meal_plan_breakfast_values to flip the default.
  const flag = String(store?.meal_plan_breakfast_values ?? '').trim().toUpperCase();
  const breakfast = flag !== 'NEVER';

  // Room code — first room's room_type_id (assuming we already filtered
  // bookings to ones covering this physical room).
  const roomCode = rooms.find(r => String(r?.room_type_id) === String(roomPlatformId))?.room_type_id
                 ?? rooms[0]?.room_type_id
                 ?? '';

  return {
    external_id,
    room_code:          String(roomCode),
    check_in,
    check_out,
    guest_count:        guests || 1,
    breakfast_included: !!breakfast,
    status,
    raw_data:           b,
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function bookingCoversRoom(b, roomPlatformId) {
  const rooms = Array.isArray(b.rooms) ? b.rooms : [];
  return rooms.some(r => String(r?.room_type_id ?? '') === String(roomPlatformId));
}

function bookingOverlapsWindow(b, fromIso, toIso) {
  const arr = toIsoDate(b.arrival);
  const dep = toIsoDate(b.departure);
  if (!arr || !dep) return false;
  // Overlap: arrival <= toIso AND departure >= fromIso
  return arr <= toIso && dep >= fromIso;
}

function toIsoDate(s) {
  if (!s) return '';
  return String(s).slice(0, 10);
}

void supabase;
